packages:
  - 'angular-webpack/'
  # - 'astro/'
  - 'kolibri-library/app/'
  - 'kolibri-library/components/'
  - 'kolibri-library/components/adapters/angular/'
  - 'kolibri-library/components/adapters/react/'
  - 'kolibri-library/components/adapters/vue/'
  - 'kolibri-library/schema/'
  - 'kolibri-library/theme/'
  - 'kolibri-theme/'
  # - 'next.js/'
  # - 'preact-webpack/'
  - 'react-vite/'
  - 'react-webpack/'
  - 'solid-webpack/'
  - 'static-page/'
  - 'svg2font/'
  - 'vue-vite/'
  - 'vue-webpack/'
